### PR TITLE
Fix "dereferencing type-punned pointer will break strict-aliasing" warn

### PR DESCRIPTION
**Pull request by kxepal**
COUCHDB-2588

cc @davisp

### CODE REVIEW

**Comment by davisp** [comment]
I'm pretty sure this PR is wrong. The error is definitely a weird one. This appears to be a decent answer on the basic question:

http://stackoverflow.com/questions/17676060/warning-dereferencing-type-punned-pointer-will-break-strict-aliasing-rules-eve

Notice that there's a comment to the effect that the compiler has to allow the cast to void*, though that's not what we want and I assume its then re-casting to void** (which should probably work but is rather quite dirty). I think we either need to do something like void* tmp = (void*) &dest; and then pass &tmp to the function or some other sort of funky thing to force the compiler to understand that we may be changing &dest during that function call.

**Comment by kxepal** [comment]
@davisp Thanks! I agree, the fix was a bit naive. Updated PR according your suggestion. Going to update https://github.com/apache/couchdb-khash/pull/1 as well.

**Comment by davisp** [comment]
Hrm. That still worries me a bit. I think I'm gonna ask on erlang-questions to see if anyone has anything to say about this.

**Comment by kxepal** [comment]
I searched over github for references of similar code: no one doing such deferencing fix. The only two examples that are close to are:
https://github.com/erlang/otp/blob/74a95b3d511177a9b35c2b0272b9ca5511b6f750/erts/example/matrix_nif.c
https://github.com/ninenines/esdl2/blob/ffd1173d7c70c57c3d184f4542e592f56030b259/c_src/sdl_window.c

May be others just didn't use "-Werror" option or don't target on FreeBSD system, but the last is the reason for this fix.

If you need any additional information for erlang-question post let me know.

**Comment by davisp** [comment]
This still makes me a bit nervous with my reading of the strict aliasing rule so I did some more reading as well. These two posts were quite helpful:

https://mail.gnome.org/archives/gtk-devel-list/2004-April/msg00196.html
http://cboard.cprogramming.com/c-programming/93006-pointer-pointer-void-dereferencing-type-punned-pointer-strict-aliasing-rule.html

I'm pretty sure that assigning the value to tmp, and then taking the reference of tmp is still actually aliasing even though the compiler is silent about it.

However, the approach suggested in those two articles is to declare a `void*` variable, take the reference of that, and then assign the result after the function call to the final pointer which makes more sense and doesn't seem like it could be considered aliasing.

https://gist.github.com/davisp/4ded9ec4244d22d2685f

Also, I should have noted, that for Windows you have to define your variables up top, the diff I linked does that as well which is important.

**Comment by kxepal** [comment]
Interesting...Yes, your patch did a trick. Will you land it or should I apply it to my PR?

**Comment by davisp** [comment]
I figured I'd let you do this one and khash. You found it after all.

**Comment by kxepal** [comment]
@davisp Thank you! Both PRs are updated.

**Comment by davisp** [comment]
+1

**Pull request merged**
