### PR TITLE
Change minimum Erlang to OTP 19

### PR DESCRIPTION
**Pull request by jaydoane**

### CODE REVIEW

**Comment by iilyak** [comment]
I think we need to remove `test/b64url_rand.erl` file as part of this PR.

**Comment by jaydoane** [comment]
@iilyak I've removed test/b64url_rand.erl and refactored to use direct `rand:uniform` calls.

**Comment by iilyak** [comment]
I found couple more places to update
- https://github.com/apache/couchdb-b64url/blob/master/test/benchmark.escript#L118
- https://github.com/apache/couchdb-b64url/blob/master/test/benchmark.escript#L140

**Comment by jaydoane** [comment]
Good catch Ilya! I replaced those you mentioned and confirmed that the benchmark is working:
```
$ ./test/benchmark.escript 1 1 2 1
nif :        2172064 bytes /   1 seconds =     2172064.00 bps
erl :         396128 bytes /   1 seconds =      396128.00 bps
```

**Review by iilyak — APPROVED** [review]
+1

**Pull request merged**
